# Generated by Django 5.0.1 on 2024-03-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=255)),
                ('teamlead', models.CharField(max_length=255)),
                ('taskname', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('assignmentdate', models.DateField()),
                ('submissiondate', models.DateField()),
                ('request', models.CharField(max_length=255)),
            ],
        ),
    ]
