# Generated by Django 5.0.1 on 2024-04-20 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_addrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projecttitle', models.CharField(max_length=255)),
                ('createddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('createddate', models.DateField()),
                ('updateddate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='addrequest',
        ),
        migrations.DeleteModel(
            name='addtask',
        ),
        migrations.AddField(
            model_name='project',
            name='list_of_todos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='api.todo'),
        ),
    ]
